services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./apps/api:/app
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
